const mongoose = require('mongoose');
const Order = require('../models/Order');
const User = require('../models/User');
require('dotenv').config();

async function createTestOrder() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/sonicmart');
    console.log('📦 Connected to MongoDB');

    // Find or create a test user
    let testUser = await User.findOne({ email: 'test@example.com' });
    if (!testUser) {
      testUser = new User({
        name: 'Test User',
        email: 'test@example.com',
        password: 'hashedpassword123',
        role: 'user'
      });
      await testUser.save();
      console.log('👤 Created test user');
    }

    // Create a test order with the new order number system
    const testOrder = new Order({
      user: testUser._id,
      orderItems: [
        {
          name: 'Premium DJ Speakers 12',
          quantity: 1,
          price: 3027,
          sku: 'DJS-12-001',
          image: '/images/DJSpeaker1.png',
          product: new mongoose.Types.ObjectId() // Create a dummy ObjectId
        }
      ],
      shippingAddress: {
        fullName: 'Test User',
        address: 'Room No 1, Zarina Bai Chawl Bheram Nagar',
        city: 'Mumbai',
        state: 'Maharashtra',
        zipCode: '400102',
        country: 'India',
        phone: '+91 9876543210'
      },
      paymentMethod: 'cod',
      paymentResult: {
        status: 'pending'
      },
      itemsPrice: 3027,
      taxPrice: 0,
      shippingPrice: 0,
      totalPrice: 3047, // Adding ₹20 COD charges
      orderStatus: 'confirmed',
      isPaid: false,
      isDelivered: false
      // orderNumber will be auto-generated by pre-save middleware
    });

    const savedOrder = await testOrder.save();
    
    console.log('\n🎉 Test order created successfully!');
    console.log('='.repeat(50));
    console.log(`📝 Order ID: ${savedOrder._id}`);
    console.log(`🏷️  Order Number: ${savedOrder.orderNumber}`);
    console.log(`📱 Display ID: #${savedOrder._id.toString().slice(-8).toUpperCase()}`);
    console.log(`💰 Total: ₹${savedOrder.totalPrice}`);
    console.log(`📊 Status: ${savedOrder.orderStatus}`);
    console.log(`📅 Created: ${savedOrder.createdAt}`);
    
    console.log('\n✅ Now you should see proper order numbers in the frontend!');
    console.log('🔄 Refresh your My Orders page to see the updated display.');

  } catch (error) {
    console.error('❌ Error creating test order:', error);
  } finally {
    await mongoose.disconnect();
    console.log('\n📦 Disconnected from MongoDB');
    process.exit(0);
  }
}

// Run the test
createTestOrder();